# Generated by Django 5.1.7 on 2025-03-16 15:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=200)),
                ('content', tinymce.models.HTMLField(help_text='Content of the blog post')),
                ('image', models.ImageField(help_text='Upload your blog post image', upload_to='blog/image')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('comments_count', models.PositiveIntegerField(default=0, editable=False, help_text='Number of comments')),
                ('share_count', models.PositiveIntegerField(default=0, editable=False, help_text='Number of shares')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('disabled', 'Disabled')], default='draft', help_text='Status of the blog post', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name, e.g., Technology', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the comment', max_length=100)),
                ('email', models.EmailField(help_text='Email of the comment', max_length=254)),
                ('message', tinymce.models.HTMLField(help_text='Message of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name, e.g., Django', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
    ]
